import random
import time
def wand_generator():
  core = ["Unicorn hair", "Dragon heartstring", "Phoenix feather"]
  length = ["9 inches", "10 inches", "11 inches", "12 inches", "13 inches", "14 inches"]
  wood = ["Acacia", "Ash", "Beech", "Blackthorn", "Cedar", "Cherry", "Chestnut", "Cypress", "Elder", "Elm", "English oak", "Fir", "Hawthorn", "Hazel", "Holly", "Hornbeam", "Mahogany", "Rosewood", "Vine", "Walnut", "Willow", "Yew"]
  global wand_wood
  wand_wood = random.choice(wood)
  global wand_core
  wand_core = random.choice(core)
  global wand_length
  wand_length = random.choice(length)
  result = "This wand is made of " + wand_wood + " wood, has a core of " + wand_core + ", and has a length of " + wand_length + "."
  return result
def startgame():
  print('  On your birthday, you recieved a acceptance letter form Hogwarts School of Witchcraft and Wizardry by a giant named Hagrid. You were very confused.')
  print('')
  input('(Press enter to continue when the text stops. Make sure not to skip the parts where you need to input information.)')
  print('')
  print("Hagrid explained to you that there was a magical population and that they keep a magic a secret to muggles (or non-magical humans).")
  print('')
  time.sleep(0.5)
  print("The acceptance letter from Hogwarts contained a list of items you needed to buy, a ticket to the train at the station 9 3/4, and a letter to you saying, Dear...")
  print('')
  gender = input("Are you a boy or girl?(type boy or girl)")
  print('')
  surname = input("What is your last name?(Make the first letter of your last name uppercase.)")
  print('')
  if gender == "boy":
    print("Dear Mr. " + surname + ",")
  else:
    print("Dear Mrs. " + surname + ",")
  print('')
  print("We are pleased to inform you that you have a place at Hogwarts School of Witchcraft and Wizardry.")
  time.sleep(0.5)
  print("Please find enclosed a list of all necessary books and equipment.")
  time.sleep(0.5)
  print('')
  print("Term begins on 1 September. We await your owl by no later than 31 July.")
  print('')
  time.sleep(0.5)
  print("Yours truly, Albus Dumbledore.")
  input()
  time.sleep(0.5)
  print("You wonder about how you will get to platform 9 3/4, but Hagrid explains that you have to run between the platforms 9 and 10. You think he's going mad, but you say nothing because you don't want to be rude.")
  time.sleep(0.5)
  input()
  print("You read the list of items you are very surprised at what you need to buy. Dragon hide? Magical books?")
  time.sleep(0.5)
  input()
  print("Hagrid leads you down to Diagon Alley. You buy:")
  time.sleep(0.5)
  print('> Three Sets of Plain Work Robes (Black),')
  time.sleep(0.25)
  print('> One Plain Pointed Hat (Black) for day wear,')
  time.sleep(0.25)
  print('> One Pair of Protective Gloves (dragon hide or similar),')
  time.sleep(0.25)
  print('> One Winter Cloak (Black, silver fastenings),')
  time.sleep(0.25)
  print('> The Standard Book of Spells, Grade 1 by Miranda Goshawk,')
  time.sleep(0.25)
  print('> A History of Magic by Bathilda Bagshot,')
  time.sleep(0.25)
  print('> Magical Theory by Adalbert Waffling,')
  time.sleep(0.25)
  print("> A Beginner's Guide to Transfiguration by Emeric Switch,")
  time.sleep(0.25)
  print('> One Thousand Magical Herbs and Fungi by Phyllida Spore,')
  time.sleep(0.25)
  print('> Magical Drafts and Potions by Arsenius Jigger,')
  time.sleep(0.25)
  print('> Fantastic Beasts and Where to Find Them by Newt Scamander,')
  time.sleep(0.25)
  print('> The Dark Forces: A Guide to Self-Protection by Quentin Trimble,')
  time.sleep(0.25)
  print('> 1 Cauldron (pewter, standard size 2),')
  time.sleep(0.25)
  print('> 1 set of glass or crystal phials,')
  time.sleep(0.25)
  print('> 1 telescope,')
  time.sleep(0.25)
  print('> and 1 set of brass scales.')
  time.sleep(0.25)
  input()
  print(' As you walk into Eeylops Owl Emporium, you spot the most beautiful owl,')
  print('with brown wings and a beige body. Two blue eyes stare affectionately back at you.')
  print('You tell the store keeper you want that owl.')
  print('')
  owl_Name = input('You get it, and name it...(Type what you want to name your owl.)')
  print('')
  print(owl_Name + '. You name your beautiful owl ' + owl_Name + '.')
  print("You feel sad to already have send her off, but you do with a letter saying you want to go to Hogwarts.")
  input()
  print(" You walk into Ollivander's. You see an old man, his wide, pale eyes shining like moons through the gloom of the shop.")
  print('"I have been awaiting you," he says.')
  name = input('Then he pauses. "What is your name?"(Type your first name.)')
  print('')
  print('You say,"I am ' + name + '."')
  print('"Ah, ' + name +'." he says.')
  wand_Hand = input('"Which hand is your wand hand?" he asks.(Type right or left)')
  print('')
  print('You say, "My ' + wand_Hand + ' hand."')
  print('"Ok, then. Stick your ' + wand_Hand + ' hand in front."')
  print('You do as he says.')
  print('"Now, now, let me see here." he says as he scans an aisle of wands.')
  input()
  print('"And remember, the wand chooses the wizard." he adds.')
  print('"Ah, here we are." he says. He takes a wand out from the aisle.')
  print('"' + wand_generator() + '" he says.')
  print('"Try it." he says.')
  input()
  print('You take it but you are unsure what to do with it.')
  print('"Just wave it at that shelf." he says. He points at a shelf that has it books slanted.')
  input()
  print('You wave it at that shelf. The books in the shelf fly out.')
  print('"Oh, dear" he says.')
  print('He takes the wand from you an instant later and uses his own wand to make make the books fly back to the shelf.')
  input()
  print('He walks down another aisle of wands and takes one out.')
  print('"' + wand_generator() + '" he says.')
  print('"Wave it at the plants to water them." he says. He points to a few roses, looking dried.')
  input()
  print('You wave it at the plants. They dry up until they are brown.')
  print('He takes it from you and waters them.')
  print('He goes into an aisle of wands and he takes out one very slowly.')
  input()
  print('"' + wand_generator() + '" he says.')
  print('"Just hold it." he says.')
  input()
  print("You take it. The second your fingers touch it you feel and energy flow inside you that you couldn't explain. You feel a sudden warmness spread into your hand.")
  print('"That wand is the one that chose you." he says.')
  input()
  print("You leave the store after that, being astonished by the experience in Ollivander's.")
  print('')
  print('As you walk out of the store, Hagrid asks you,"Got your wand?"')
  input()
  print('"Yep," you answer.')
  print('You go back home to pack your trunk.')
  input()
  print('As the weeks go by, you anticipate for the time when you will go to Hogwarts.')
  print ('Finally, the time has come! September 1st!')
  input()
  print('Hagrid leads you to where the train station is, and he leads you to platform 9 3/4.')
  print('Unfortunately, he has to do an errand, and leaves you all alone.')
  input()
  print('Scared, you walk down the platform and see a family going through the barrier. You hurry towards them.')
  print('One of them notices you. They ask you if this is your first time going to Hogwarts.')
  print('Unable to talk, you nod.')
  input()
  print('They explain that you have to walk in the barrier when no muggles are watching.')
  print('You walk towards the barrier, breaking into a trot.')
  input()
  print('You feel the warm steam from the train and realized that you passed through the barrier.')
  print('')
startgame()